version: "3.8"
services:
  app:
    container_name: dgraph-app
    image: ${DOCKER_REPOSITORY}:latest
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${SPRING_DATASOURCE_DRIVERCLASSNAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    links:
      - postgresql
    volumes:
      - ./files:/var/lib/dgraph
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /tmp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  files: