name: DGraph
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B package

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    env:
      REPO: ${{ secrets.DOCKER_REPOSITORY}}
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t $REPO:latest
      - name: Push docker image
        run: docker push $REPO